declare const $: any;
declare const _: any;
declare const toastr: any;
declare const YAML: any;
declare const Mvu: any;
declare function generate(config: any): Promise<any>;
declare function generateRaw(config: any): Promise<any>;
declare function getCharWorldbookNames(name: string): { primary: string | null; additional: string[] };
declare function getWorldbook(name: string): Promise<any[]>;
declare function updateWorldbookWith(name: string, updater: any): Promise<any>;
declare function createWorldbookEntries(name: string, entries: any[]): Promise<any>;
declare function getLastMessageId(): number;
declare function getCurrentMessageId(): number;
declare function getChatMessages(id: number): any[];
declare function createChatMessages(msgs: any[]): Promise<void>;
declare function getCharLorebooks(): { primary: string | null; additional: string[] };
declare function getLorebookEntries(name: string): Promise<any[]>;
declare function getVariables(opts: any): any;
declare function getAllVariables(): Record<string, any>;
declare function eventOn(event: string, callback: (...args: any[]) => void): void;
declare function eventRemoveListener(event: string, callback: (...args: any[]) => void): void;
declare const tavern_events: Record<string, string>;
declare const iframe_events: Record<string, string>;
declare function generateRaw(config: any): Promise<any>;
declare function getModelList(custom_api: { apiurl: string; key?: string }): Promise<string[]>;
declare function setChatMessages(msgs: any[], opts?: any): Promise<void>;
declare const Mvu: any;
